# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false


# Setup
title:               Diario in codice
tagline:             'imparare nuove parole'
description:         'Diario in codice, indice'
url:                 http://www.limulo.net
baseurl:             ''
#paginate:            5

# About/contact
author:
  name:              Nicola Ariutti
  url:               https://twitter.com/nicolaariutti
  email:             nicola@limulo.net

# Custom vars
version:             1.0.0
